module.exports = [
  {
    ExponentUtil: [
      { reload: 'function' },
      { getCurrentLocaleAsync: 'function' },
      { getCurrentDeviceCountryAsync: 'function' },
      { getCurrentTimeZoneAsync: 'function' },
    ],
  },
  { ExponentScreenOrientation: [{ allow: 'function' }] },
  {
    ExponentSecureStore: [
      { setValueWithKeyAsync: 'function' },
      { getValueWithKeyAsync: 'function' },
      { deleteValueWithKeyAsync: 'function' },
      { ALWAYS: 'number' },
      { WHEN_UNLOCKED_THIS_DEVICE_ONLY: 'number' },
      { ALWAYS_THIS_DEVICE_ONLY: 'number' },
      { AFTER_FIRST_UNLOCK: 'number' },
      { WHEN_UNLOCKED: 'number' },
      { WHEN_PASSCODE_SET_THIS_DEVICE_ONLY: 'number' },
      { AFTER_FIRST_UNLOCK_THIS_DEVICE_ONLY: 'number' },
    ],
  },
  { ExponentGoogle: [{ logInAsync: 'function' }] },
  {
    ExponentNotifications: [
      { getDevicePushTokenAsync: 'function' },
      { getExponentPushTokenAsync: 'function' },
      { presentLocalNotification: 'function' },
      { scheduleLocalNotification: 'function' },
      { cancelScheduledNotification: 'function' },
      { cancelAllScheduledNotifications: 'function' },
      { getBadgeNumberAsync: 'function' },
      { setBadgeNumberAsync: 'function' },
    ],
  },
  {
    ExponentFileSystem: [
      { getInfoAsync: 'function' },
      { readAsStringAsync: 'function' },
      { writeAsStringAsync: 'function' },
      { deleteAsync: 'function' },
      { moveAsync: 'function' },
      { copyAsync: 'function' },
      { makeDirectoryAsync: 'function' },
      { readDirectoryAsync: 'function' },
      { downloadAsync: 'function' },
      { downloadResumableStartAsync: 'function' },
      { downloadResumablePauseAsync: 'function' },
      { addListener: 'function' },
      { removeListeners: 'function' },
      { cacheDirectory: 'string' },
      { documentDirectory: 'string' },
    ],
  },
  { ExponentErrorRecovery: [{ setRecoveryProps: 'function' }] },
  {
    ExponentGyroscope: [
      { setUpdateInterval: 'function' },
      { addListener: 'function' },
      { removeListeners: 'function' },
    ],
  },
  { ExponentAppLoadingManager: [{ finishedAsync: 'function' }] },
  { ExponentBlurViewManager: [] },
  { ExponentContacts: [{ getContactsAsync: 'function' }] },
  {
    ExponentSpeech: [
      { speak: 'function' },
      { stop: 'function' },
      { isSpeaking: 'function' },
      { addListener: 'function' },
      { removeListeners: 'function' },
    ],
  },
  {
    ExponentMagnetometer: [
      { setUpdateInterval: 'function' },
      { addListener: 'function' },
      { removeListeners: 'function' },
    ],
  },
  { ExponentSQLite: [{ exec: 'function' }] },
  {
    ExponentAmplitude: [
      { initialize: 'function' },
      { setUserId: 'function' },
      { setUserProperties: 'function' },
      { clearUserProperties: 'function' },
      { logEvent: 'function' },
      { logEventWithProperties: 'function' },
      { setGroup: 'function' },
    ],
  },
  { ExponentFacebook: [{ logInWithReadPermissionsAsync: 'function' }] },
  {
    ExponentFingerprint: [
      { hasHardwareAsync: 'function' },
      { isEnrolledAsync: 'function' },
      { authenticateAsync: 'function' },
    ],
  },
  { ExponentFontLoader: [{ loadAsync: 'function' }] },
  { ExponentDocumentPicker: [{ getDocumentAsync: 'function' }] },
  {
    ExponentImagePicker: [
      { launchCameraAsync: 'function' },
      { launchImageLibraryAsync: 'function' },
    ],
  },
  {
    ExponentGLObjectManager: [
      { createObjectAsync: 'function' },
      { destroyObjectAsync: 'function' },
    ],
  },
  { ExponentLinearGradientManager: [] },
  {
    ExponentMagnetometerUncalibrated: [
      { setUpdateInterval: 'function' },
      { addListener: 'function' },
      { removeListeners: 'function' },
    ],
  },
  { ExponentScopedModuleRegistry: [] },
  {
    ExponentLegacyAsyncLocalStorage: [
      { multiGet: 'function' },
      { getAllKeys: 'function' },
      { isMigrationDone: 'function' },
      { setMigrationDone: 'function' },
    ],
  },
  {
    ExponentVideoManager: [
      { setFullscreen: 'function' },
      { ScaleToFill: 'string' },
      { ScaleAspectFill: 'string' },
      { ScaleAspectFit: 'string' },
      { ScaleNone: 'string' },
    ],
  },
  {
    ExponentBarCodeScannerManager: [
      { BarCodeType: 'object' },
      { Type: 'object' },
      { TorchMode: 'object' },
    ],
  },
  {
    ExponentSegment: [
      { initializeIOS: 'function' },
      { initializeAndroid: 'function' },
      { identify: 'function' },
      { identifyWithTraits: 'function' },
      { track: 'function' },
      { trackWithProperties: 'function' },
      { screen: 'function' },
      { screenWithProperties: 'function' },
      { reset: 'function' },
      { flush: 'function' },
    ],
  },
  {
    ExponentPedometer: [
      { getStepCountAsync: 'function' },
      { watchStepCount: 'function' },
      { stopWatchingStepCount: 'function' },
      { isAvailableAsync: 'function' },
      { addListener: 'function' },
      { removeListeners: 'function' },
    ],
  },
  {
    ExponentAccelerometer: [
      { setUpdateInterval: 'function' },
      { addListener: 'function' },
      { removeListeners: 'function' },
    ],
  },
  { ExponentGLViewManager: [] },
  {
    ExponentWebBrowser: [
      { dismissBrowser: 'function' },
      { openBrowserAsync: 'function' },
    ],
  },
  { ExponentKeepAwake: [{ activate: 'function' }, { deactivate: 'function' }] },
  {
    ExponentAV: [
      { setAudioIsEnabled: 'function' },
      { setAudioMode: 'function' },
      { loadForSound: 'function' },
      { unloadForSound: 'function' },
      { setStatusForSound: 'function' },
      { getStatusForSound: 'function' },
      { setStatusUpdateCallbackForSound: 'function' },
      { setErrorCallbackForSound: 'function' },
      { loadForVideo: 'function' },
      { unloadForVideo: 'function' },
      { setStatusForVideo: 'function' },
      { getStatusForVideo: 'function' },
      { prepareAudioRecorder: 'function' },
      { startAudioRecording: 'function' },
      { pauseAudioRecording: 'function' },
      { stopAudioRecording: 'function' },
      { getAudioRecordingStatus: 'function' },
      { unloadAudioRecorder: 'function' },
    ],
  },
  {
    ExponentConstants: [
      { getWebViewUserAgentAsync: 'function' },
      { isDevice: 'boolean' },
      { linkingUri: 'string' },
      { deviceId: 'string' },
      { expoVersion: 'string' },
      { manifest: 'object' },
      { deviceName: 'string' },
      { platform: 'object' },
      { statusBarHeight: 'number' },
      { sessionId: 'string' },
      { systemFonts: 'object' },
      { deviceYearClass: 'number' },
      { appOwnership: 'string' },
    ],
  },
  { ExponentPermissions: [{ getAsync: 'function' }, { askAsync: 'function' }] },
  {
    ExponentLocation: [
      { getProviderStatusAsync: 'function' },
      { getCurrentPositionAsync: 'function' },
      { watchPositionImplAsync: 'function' },
      { watchDeviceHeading: 'function' },
      { removeWatchAsync: 'function' },
      { geocodeAsync: 'function' },
      { reverseGeocodeAsync: 'function' },
      { addListener: 'function' },
      { removeListeners: 'function' },
    ],
  },
];
